[project]
name = "health-management-bot"
version = "0.1.0"
description = "Health management bot"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aerich>=0.9.2",
    "aiogram>=3.22.0",
    "asyncpg>=0.30.0",
    "pydantic-settings>=2.12.0",
    "python-dotenv>=1.2.1",
    "tortoise-orm>=0.25.1",
]
